### ISSUE TITLE
Minor fix for French language

### ISSUE THREAD

**Issue by benoitkugler** [moul/number-to-words#35]
It seems that _quatre-vingt-un_ is better than _quatre-vingt un_ in french.
Is there a particular reason not to be consistent for 8x ? 

If not, it can be fixed with 
`
word := fmt.Sprintf("%s-%s", frenchTens[tens], frenchUnits[units]) 
`
`
words = append(words, word)
`

Thanks for your work !

**Comment by moul** [comment]
Good catch :)

Would you make a PR?

Thanks!

**Comment by moul** [comment]
Fixed by #51 

Thanks again :)
